name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-build-and-test.yml
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest]
        python-version: [3.10, 3.11]
    with:
      runs-on: ${{ matrix.runs-on }}
      python-version: ${{ matrix.python-version }}
      run-lint: true
      requirements-file: requirements.txt
